# Generated by Django 5.2.6 on 2026-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='parent', max_length=20),
        ),
    ]
