# Generated by Django 5.2.6 on 2026-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_updated_at_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
