# Generated by Django 5.2.6 on 2026-06-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('children_limit', models.IntegerField(default=1)),
                ('subjects_limit', models.IntegerField(default=1)),
                ('lessons_limit', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(db_index=True, default='free', max_length=20),
        ),
    ]
