# Generated by Django 5.2.6 on 2026-06-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
