# Generated by Django 5.2.6 on 2026-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_has_account_child_invite_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
