# Generated by Django 5.2.6 on 2026-05-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_email_child_last_name'),
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprompttemplate',
            options={'ordering': ['subject', 'name'], 'verbose_name': 'AI Prompt Template', 'verbose_name_plural': 'AI Prompt Templates'},
        ),
        migrations.AlterModelOptions(
            name='generatedlessonmemory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generated Lesson Memory', 'verbose_name_plural': 'Generated Lesson Memories'},
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aiprompttemplate',
            name='template',
            field=models.TextField(help_text='\nUse variables:\n{{subject}},\n{{topic}},\n{{age}},\n{{grade}},\n{{interests}}\n'),
        ),
        migrations.AlterField(
            model_name='generatedlessonmemory',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_memories', to='children.child'),
        ),
        migrations.AlterField(
            model_name='generatedlessonmemory',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
