name: CI/CD Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t alexandrgrebennikov/dev-range-backend:latest .

      - name: Push image
        run: |
          docker push alexandrgrebennikov/dev-range-backend:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. СНАЧАЛА копируем инфраструктуру
      - name: Copy nginx + compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: admin_diego
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "nginx.conf,docker-compose.yml"
          target: "/home/admin_diego/dev_range/"

      # 2. ПОТОМ деплой
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: admin_diego
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/admin_diego/dev_range

            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d --force-recreate

            docker image prune -f