name: CI/CD Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: |
          docker build -t alexandrgrebennikov/dev-range-backend:latest .
          docker push alexandrgrebennikov/dev-range-backend:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: admin_diego
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd /home/admin_diego/dev_range

            echo ">>> Updating code from git..."
            git fetch --all
            git reset --hard origin/master

            echo ">>> Pulling latest Docker images..."
            docker compose pull

            echo ">>> Recreating containers..."
            docker compose up -d --force-recreate

            echo ">>> Cleaning old images..."
            docker image prune -f

            echo ">>> Deployment finished successfully"